### PR TITLE
Introduced AppImage build system

### PR DESCRIPTION
**Pull request by ebababi**
I believe a good way to ease access to this application is distributing as an AppImage.

Leveraging [appimage-builder](https://github.com/AppImageCrafters/appimage-builder) a configuration has been created to generate an AppImage bundle of the project. Minimal changes to the rest of the code base include:
* Git ignoring temporary files and generated artifacts.
* Converting XPM icon to PNG and storing in `addons`. This was an `appimage-builder` requirement.
* When `dist_path` is not explicitly set, resolve to the script path instead of the current path.

One may explore [GitHub Actions to automatically build the AppImage bundle](https://appimage-builder.readthedocs.io/en/latest/hosted-services/github-actions.html).

I have tried the generated AppImage on Ubuntu 20.04, however I haven't tried on any other distribution.

### CODE REVIEW

**Comment by tiktaalik-dev** [comment]
Hi Nikolaos,

Sorry for the late reply, it's been kind of hectic for me lately.
Thanks so much for this contribution! It's a great idea making an AppImage!
But may I ask for you to create a '/feature/AppImage' branch, please? Or if you allow it in your pull request maybe I could do it myself. I reckon GitHub has that feature, if I remember correctly.
Thanks in advance for your help to improve this software!

Cheers,
Rigo

**Comment by ebababi** [comment]
Hi Rigo,

Of course you can do any modification you see fit.

I'm not sure how to open a new branch pulling from my repository, but if you can feel free.

Regards,

Nikolaos

**Comment by tiktaalik-dev** [comment]
Hi again Nikolaos,
Thanks again for your contribution :smile: 
I'm going to experiment now with this configuration and then merge it on the master branch. Please let me know how do you want to be credited for your work when I do the final merge. Maybe you want to add an email address next to your name? Or your GitHub username?

Cheers,
Rigo.

**Comment by ebababi** [comment]
Hi Rigo,

Thank you for the consideration. I have no preference and even no mention at all is also OK. I leave it to your discretion.

Regards,
Nikolaos

**Pull request merged**
